### ISSUE TITLE
Empty output

### ISSUE THREAD

**Issue by besi** [INTI-CMNB/PcbDraw#12]
Hy there. I wanted to use `PcbDraw` on my mac but that does not seem possible at the moment. However, I have a Linux Server (Headless) on which I did install kicad along with imagemagick and pcbdraw.

Now when I run `PcbDraw` I get a set of warnings about some components that can't be found.

At the end there is an output.png created and it has 1140 x 600 pixels the image itself is empty:

I would assume that even when the components aren't found that I would still see the board and the silk screen being rendered. 

**Update**: 
I did try other options and apparently only the `png` and `jpg` option result in an empty image. The `svg` output works fine.
I'll update my 

## output.png
[![output](https://user-images.githubusercontent.com/160412/119795975-40d7d780-bed9-11eb-950f-8418a968b12f.png)](https://user-images.githubusercontent.com/160412/119795975-40d7d780-bed9-11eb-950f-8418a968b12f.png)

## output.jpg

![output](https://user-images.githubusercontent.com/160412/119797075-32d68680-beda-11eb-8bb2-1499a3e84548.jpg)

## output.svg

![Screenshot 2021-05-27 at 10 56 22](https://user-images.githubusercontent.com/160412/119797044-2e11d280-beda-11eb-8ef1-392169a615bb.png)

**Comment by set-soft** [comment]
Install the Debian package, it will pull all the dependencies.
